services:
  postgres:
    environment:
      - POSTGRES_MULTIPLE_DATABASES=java,python,csharp,dst_reference

  dst-reference-init:
    image: maven:3.8.5-openjdk-17
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ../../orm-reference-implementations/dst/dst21.assignment1.berndstainer01634260/ass1-jpa/src/main/java:/app/dst-src:ro
      - ../../orm-reference-implementations/dst/dst21.assignment1.berndstainer01634260/ass1-jpa/src/main/resources:/app/dst-res:ro
      - ../../orm-reference-implementations/dst-runner/pom.xml:/app/pom.xml:ro
      - ../../orm-reference-implementations/dst-runner/src/main/java/GenerateDatabase.java:/app/runner-src/GenerateDatabase.java:ro
      - ../../orm-reference-implementations/dst-runner/src/main/resources/META-INF/persistence.xml:/app/runner-res/persistence.xml:ro
      - ../../orm-reference-implementations/dst-runner/src/main/resources/META-INF/orm.xml:/app/runner-res/orm.xml:ro
      - ../../orm-reference-implementations/dst-runner/entrypoint.sh:/app/entrypoint.sh:ro
    command: sh /app/entrypoint.sh

  migra-runner:
    depends_on:
      dst-reference-init:
        condition: service_completed_successfully
