/*
 * generated by Xtext 2.28.0
 */
package org.big.orm.language.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.big.orm.language.JavaModelRuntimeModule;
import org.big.orm.language.JavaModelStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JavaModelIdeSetup extends JavaModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JavaModelRuntimeModule(), new JavaModelIdeModule()));
	}
	
}
