/*
 * generated by Xtext 2.28.0
 */
package org.big.orm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OrmModelStandaloneSetup extends OrmModelStandaloneSetupGenerated {

	public static void doSetup() {
		new OrmModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
