/*
 * generated by Xtext 2.28.0
 */
package org.big.orm.language.java;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JavaModelStandaloneSetup extends JavaModelStandaloneSetupGenerated {

	public static void doSetup() {
		new JavaModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
