/*
 * generated by Xtext 2.28.0
 */
package org.big.orm.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class OrmModelScopeProvider extends AbstractOrmModelScopeProvider {

}
