/*
 * generated by Xtext 2.28.0
 */
package org.big.orm.tests

import com.google.inject.Inject
import org.big.orm.ormModel.OrmModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(OrmModelInjectorProvider)
class OrmModelParsingTest {
	@Inject
	ParseHelper<OrmModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			orm_model xtext
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
