/*
 * generated by Xtext 2.34.0
 */
package org.big.orm.language.java.tests

import com.google.inject.Inject
import org.big.orm.language.java.javaModel.JavaModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(JavaModelInjectorProvider)
class JavaModelParsingTest {
	@Inject
	ParseHelper<JavaModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
