/*
 * generated by Xtext 2.28.0
 */
package org.big.orm.language;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JavaModelRuntimeModule extends AbstractJavaModelRuntimeModule {
}
