/*
 * generated by Xtext 2.28.0
 */
package org.big.orm.ide;

import org.big.orm.ide.command.CommandService;
import org.big.orm.ide.symbol.OrmDocumentSymbolKindProvider;
import org.big.orm.ide.symbol.OrmDocumentSymbolNameProvider;
import org.eclipse.xtext.ide.server.commands.IExecutableCommandService;
import org.eclipse.xtext.ide.server.symbol.DocumentSymbolMapper.DocumentSymbolKindProvider;
import org.eclipse.xtext.ide.server.symbol.DocumentSymbolMapper.DocumentSymbolNameProvider;

/**
 * Use this class to register ide components.
 */
public class OrmModelIdeModule extends AbstractOrmModelIdeModule {
	
	public Class<? extends DocumentSymbolNameProvider> bindDocumentSymbolNameProvider() {
		return OrmDocumentSymbolNameProvider.class;
	}
	
	public Class<? extends DocumentSymbolKindProvider> bindDocumentSymbolKindProvider() {
		return OrmDocumentSymbolKindProvider.class;
	}
	
	public Class<? extends IExecutableCommandService> bindIExecutableCommandService() {
		return CommandService.class;
	}
	
}
