/*
 * generated by Xtext 2.28.0
 */
package org.big.orm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.big.orm.OrmModelRuntimeModule;
import org.big.orm.OrmModelStandaloneSetup;
import org.big.orm.ide.diagram.OrmModelDiagramModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class OrmModelIdeSetup extends OrmModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new OrmModelRuntimeModule(), new OrmModelIdeModule(), new OrmModelDiagramModule()));
	}
	
}
